#pragma once

#include "nullable.h"

ASSUME_NONNULL_BEGIN

struct ast_expression_list;
struct ast_statement_list;
struct object_intern;
union ast_expression;
union ast_statement;
union object;

enum ast_expression_type {
  AST_ATTR,
  AST_BINEXPR_ADD,
  AST_BINEXPR_ADD_ASSIGN,
  AST_BINEXPR_AND,
  AST_BINEXPR_AND_ASSIGN,
  AST_BINEXPR_ASSIGN,
  AST_BINEXPR_FLOORDIV,
  AST_BINEXPR_FLOORDIV_ASSIGN,
  AST_BINEXPR_LOGICAL_AND,
  AST_BINEXPR_LOGICAL_OR,
  AST_BINEXPR_MATMUL,
  AST_BINEXPR_MATMUL_ASSIGN,
  AST_BINEXPR_MOD,
  AST_BINEXPR_MOD_ASSIGN,
  AST_BINEXPR_MUL,
  AST_BINEXPR_MUL_ASSIGN,
  AST_BINEXPR_OR,
  AST_BINEXPR_OR_ASSIGN,
  AST_BINEXPR_POWER,
  AST_BINEXPR_POWER_ASSIGN,
  AST_BINEXPR_SHIFT_LEFT,
  AST_BINEXPR_SHIFT_LEFT_ASSIGN,
  AST_BINEXPR_SHIFT_RIGHT,
  AST_BINEXPR_SHIFT_RIGHT_ASSIGN,
  AST_BINEXPR_SUB,
  AST_BINEXPR_SUB_ASSIGN,
  AST_BINEXPR_SUBSCRIPT,
  AST_BINEXPR_TRUEDIV,
  AST_BINEXPR_TRUEDIV_ASSIGN,
  AST_BINEXPR_XOR,
  AST_BINEXPR_XOR_ASSIGN,
  AST_CALL,
  AST_COMPARISON,
  AST_CONDITIONAL,
  AST_CONST,
  AST_DICT_COMPREHENSION,
  AST_DICT_DISPLAY,
  AST_EXPRESSION_LIST,
  AST_FSTRING,
  AST_GENERATOR_EXPRESSION,
  AST_IDENTIFIER,
  AST_INVALID,
  AST_LAMBDA,
  AST_LIST_COMPREHENSION,
  AST_LIST_DISPLAY,
  AST_SET_COMPREHENSION,
  AST_SET_DISPLAY,
  AST_SLICE,
  AST_UNEXPR_AWAIT,
  AST_UNEXPR_INVERT,
  AST_UNEXPR_NEGATIVE,
  AST_UNEXPR_NOT,
  AST_UNEXPR_PLUS,
  AST_UNEXPR_STAR,
  AST_UNEXPR_STAR_STAR,
  AST_YIELD,
  AST_YIELD_FROM,
};

enum ast_expression_type ast_expression_type(union ast_expression *expression);

enum ast_statement_type {
  AST_STATEMENT_ANNOTATION,
  AST_STATEMENT_ASSERT,
  AST_STATEMENT_ASSIGN,
  AST_STATEMENT_AUGASSIGN,
  AST_STATEMENT_BREAK,
  AST_STATEMENT_CLASS,
  AST_STATEMENT_CONTINUE,
  AST_STATEMENT_DEF,
  AST_STATEMENT_DEL,
  AST_STATEMENT_EXPRESSION,
  AST_STATEMENT_FOR,
  AST_STATEMENT_FROM_IMPORT,
  AST_STATEMENT_GLOBAL,
  AST_STATEMENT_IF,
  AST_STATEMENT_IMPORT,
  AST_STATEMENT_NONLOCAL,
  AST_STATEMENT_PASS,
  AST_STATEMENT_RAISE,
  AST_STATEMENT_RETURN,
  AST_STATEMENT_TRY,
  AST_STATEMENT_WHILE,
  AST_STATEMENT_WITH,
  AST_STATEMENT_YIELD,
  AST_STATEMENT_YIELD_FROM,
};

enum ast_statement_type ast_statement_type(union ast_statement *statement);

union object *nullable
ast_expression_as_constant(union ast_expression *expression);

union object *nullable ast_tuple_compute_constant(
    struct object_intern *intern, struct ast_expression_list *tuple);

ASSUME_NONNULL_END
