#pragma once

#include <stdint.h>

enum opcode {
  OPCODE_POP_TOP = 1,
  OPCODE_ROT_TWO = 2,
  OPCODE_ROT_THREE = 3,
  OPCODE_DUP_TOP = 4,
  OPCODE_DUP_TOP_TWO = 5,
  OPCODE_NOP = 9,
  OPCODE_UNARY_POSITIVE = 10,
  OPCODE_UNARY_NEGATIVE = 11,
  OPCODE_UNARY_NOT = 12,
  OPCODE_UNARY_INVERT = 15,
  OPCODE_BINARY_MATRIX_MULTIPLY = 16,
  OPCODE_INPLACE_MATRIX_MULTIPLY = 17,
  OPCODE_BINARY_POWER = 19,
  OPCODE_BINARY_MULTIPLY = 20,
  OPCODE_BINARY_MODULO = 22,
  OPCODE_BINARY_ADD = 23,
  OPCODE_BINARY_SUBTRACT = 24,
  OPCODE_BINARY_SUBSCR = 25,
  OPCODE_BINARY_FLOOR_DIVIDE = 26,
  OPCODE_BINARY_TRUE_DIVIDE = 27,
  OPCODE_INPLACE_FLOOR_DIVIDE = 28,
  OPCODE_INPLACE_TRUE_DIVIDE = 29,
  OPCODE_GET_AITER = 50,
  OPCODE_GET_ANEXT = 51,
  OPCODE_BEFORE_ASYNC_WITH = 52,
  OPCODE_BEGIN_FINALLY = 53,
  OPCODE_INPLACE_ADD = 55,
  OPCODE_INPLACE_SUBTRACT = 56,
  OPCODE_INPLACE_MULTIPLY = 57,
  OPCODE_INPLACE_MODULO = 59,
  OPCODE_STORE_SUBSCR = 60,
  OPCODE_DELETE_SUBSCR = 61,
  OPCODE_BINARY_LSHIFT = 62,
  OPCODE_BINARY_RSHIFT = 63,
  OPCODE_BINARY_AND = 64,
  OPCODE_BINARY_XOR = 65,
  OPCODE_BINARY_OR = 66,
  OPCODE_INPLACE_POWER = 67,
  OPCODE_GET_ITER = 68,
  OPCODE_GET_YIELD_FROM_ITER = 69,
  OPCODE_PRINT_EXPR = 70,
  OPCODE_LOAD_BUILD_CLASS = 71,
  OPCODE_YIELD_FROM = 72,
  OPCODE_GET_AWAITABLE = 73,
  OPCODE_INPLACE_LSHIFT = 75,
  OPCODE_INPLACE_RSHIFT = 76,
  OPCODE_INPLACE_AND = 77,
  OPCODE_INPLACE_XOR = 78,
  OPCODE_INPLACE_OR = 79,
  OPCODE_BREAK_LOOP = 80,
  OPCODE_WITH_CLEANUP_START = 81,
  OPCODE_WITH_CLEANUP_FINISH = 82,
  OPCODE_RETURN_VALUE = 83,
  OPCODE_IMPORT_STAR = 84,
  OPCODE_SETUP_ANNOTATIONS = 85,
  OPCODE_YIELD_VALUE = 86,
  OPCODE_POP_BLOCK = 87,
  OPCODE_END_FINALLY = 88,
  OPCODE_POP_EXCEPT = 89,
  OPCODE_HAVE_ARGUMENT = 90,
  OPCODE_STORE_NAME = 90,
  OPCODE_DELETE_NAME = 91,
  OPCODE_UNPACK_SEQUENCE = 92,
  OPCODE_FOR_ITER = 93,
  OPCODE_UNPACK_EX = 94,
  OPCODE_STORE_ATTR = 95,
  OPCODE_DELETE_ATTR = 96,
  OPCODE_STORE_GLOBAL = 97,
  OPCODE_DELETE_GLOBAL = 98,
  OPCODE_LOAD_CONST = 100,
  OPCODE_LOAD_NAME = 101,
  OPCODE_BUILD_TUPLE = 102,
  OPCODE_BUILD_LIST = 103,
  OPCODE_BUILD_SET = 104,
  OPCODE_BUILD_MAP = 105,
  OPCODE_LOAD_ATTR = 106,
  OPCODE_COMPARE_OP = 107,
  OPCODE_IMPORT_NAME = 108,
  OPCODE_IMPORT_FROM = 109,
  OPCODE_JUMP_FORWARD = 110,
  OPCODE_JUMP_IF_FALSE_OR_POP = 111,
  OPCODE_JUMP_IF_TRUE_OR_POP = 112,
  OPCODE_JUMP_ABSOLUTE = 113,
  OPCODE_POP_JUMP_IF_FALSE = 114,
  OPCODE_POP_JUMP_IF_TRUE = 115,
  OPCODE_LOAD_GLOBAL = 116,
  /* OPCODE_CONTINUE_LOOP                = 119,  // removed in 3.8 */
  /* OPCODE_SETUP_LOOP                   = 120,  // removed in 3.8 */
  /* OPCODE_SETUP_EXCEPT                 = 121,  // removed in 3.8 */
  OPCODE_SETUP_FINALLY = 122,
  OPCODE_LOAD_FAST = 124,
  OPCODE_STORE_FAST = 125,
  OPCODE_DELETE_FAST = 126,
  OPCODE_RAISE_VARARGS = 130,
  OPCODE_CALL_FUNCTION = 131,
  OPCODE_MAKE_FUNCTION = 132,
  OPCODE_BUILD_SLICE = 133,
  OPCODE_LOAD_CLOSURE = 135,
  OPCODE_LOAD_DEREF = 136,
  OPCODE_STORE_DEREF = 137,
  OPCODE_DELETE_DEREF = 138,
  OPCODE_CALL_FUNCTION_KW = 141,
  OPCODE_CALL_FUNCTION_EX = 142,
  OPCODE_SETUP_WITH = 143,
  OPCODE_EXTENDED_ARG = 144,
  OPCODE_LIST_APPEND = 145,
  OPCODE_SET_ADD = 146,
  OPCODE_MAP_ADD = 147,
  OPCODE_LOAD_CLASSDEREF = 148,
  OPCODE_BUILD_LIST_UNPACK = 149,
  OPCODE_BUILD_MAP_UNPACK = 150,
  OPCODE_BUILD_MAP_UNPACK_WITH_CALL = 151,
  OPCODE_BUILD_TUPLE_UNPACK = 152,
  OPCODE_BUILD_SET_UNPACK = 153,
  OPCODE_SETUP_ASYNC_WITH = 154,
  OPCODE_FORMAT_VALUE = 155,
  OPCODE_BUILD_CONST_KEY_MAP = 156,
  OPCODE_BUILD_STRING = 157,
  OPCODE_BUILD_TUPLE_UNPACK_WITH_CALL = 158,
  OPCODE_LOAD_METHOD = 160,
  OPCODE_CALL_METHOD = 161,
  OPCODE_CALL_FINALLY = 162, /* added in 3.8 */
  OPCODE_POP_FINALLY = 163,  /* added in 3.8 */
};

enum compare_op_arg {
  COMPARE_OP_LT = 0,
  COMPARE_OP_LE = 1,
  COMPARE_OP_EQ = 2,
  COMPARE_OP_NE = 3,
  COMPARE_OP_GT = 4,
  COMPARE_OP_GE = 5,
  COMPARE_OP_IN = 6,
  COMPARE_OP_NOT_IN = 7,
  COMPARE_OP_IS = 8,
  COMPARE_OP_IS_NOT = 9,
  COMPARE_OP_EXC_MATCH = 10,
};

static inline bool is_absjump(uint32_t opcode)
{
  switch (opcode) {
  case OPCODE_JUMP_ABSOLUTE:
  case OPCODE_JUMP_IF_FALSE_OR_POP:
  case OPCODE_JUMP_IF_TRUE_OR_POP:
  case OPCODE_POP_JUMP_IF_FALSE:
  case OPCODE_POP_JUMP_IF_TRUE:
    return true;
  default:
    return false;
  }
}

static inline bool is_jump(uint8_t opcode)
{
  switch (opcode) {
  case OPCODE_FOR_ITER:
  case OPCODE_JUMP_ABSOLUTE:
  case OPCODE_JUMP_FORWARD:
  case OPCODE_JUMP_IF_FALSE_OR_POP:
  case OPCODE_JUMP_IF_TRUE_OR_POP:
  case OPCODE_POP_JUMP_IF_FALSE:
  case OPCODE_POP_JUMP_IF_TRUE:
  case OPCODE_SETUP_FINALLY:
  case OPCODE_SETUP_WITH:
  case OPCODE_SETUP_ASYNC_WITH:
  case OPCODE_CALL_FINALLY:
    return true;
  default:
    return false;
  }
}
