/* clang-format off */
TCHAR('%', T_PERCENT,      "%")
TCHAR('&', T_AMPERSAND,    "&")
TCHAR('(', T_LPAREN,       "(")
TCHAR(')', T_RPAREN,       ")")
TCHAR('*', T_ASTERISK,     "*")
TCHAR('+', T_PLUS,         "+")
TCHAR(',', T_COMMA,        ",")
TCHAR('-', T_MINUS,        "-")
TCHAR('.', T_DOT,          ".")
TCHAR('/', T_SLASH,        "/")
TCHAR(':', T_COLON,        ":")
TCHAR(';', T_SEMICOLON,    ";")
TCHAR('<', T_LESS_THAN,    "<")
TCHAR('=', T_EQUALS,       "=")
TCHAR('>', T_GREATER_THAN, ">")
TCHAR('@', T_AT,           "@")
TCHAR('[', T_LBRACK,       "[")
TCHAR(']', T_RBRACK,       "]")
TCHAR('^', T_CARET,        "^")
TCHAR('{', T_LCURLY,       "{")
TCHAR('|', T_BAR,          "|")
TCHAR('}', T_RCURLY,       "}")
TCHAR('~', T_TILDE,        "~")

TCHAR(256, T_INDENT,                     "indent")
TDES(T_DEDENT,                           "dedent")
TDES(T_INTEGER,                          "integer")
TDES(T_FLOAT,                            "float")
TDES(T_STRING,                           "string")
TDES(T_BYTE_STRING,                      "byte string")
TDES(T_FORMAT_STRING,                    "format string")
TDES(T_RAW_STRING,                       "raw string")
TDES(T_UNICODE_STRING,                   "unicode string")
TDES(T_NEWLINE,                          "new line")
TDES(T_EOF,                              "end of file")
TDES(T_AMPERSAND_EQUALS,                 "&=")
TDES(T_ASTERISK_ASTERISK,                "**")
TDES(T_ASTERISK_ASTERISK_EQUALS,         "**=")
TDES(T_ASTERISK_EQUALS,                  "*=")
TDES(T_AT_EQUALS,                        "@=")
TDES(T_BAR_EQUALS,                       "|=")
TDES(T_CARET_EQUALS,                     "^=")
TDES(T_DOT_DOT_DOT,                      "...")
TDES(T_EQUALS_EQUALS,                    "==")
TDES(T_EXCLAMATIONMARKEQUALS,            "!=")
TDES(T_GREATER_THAN_EQUALS,              ">=")
TDES(T_GREATER_THAN_GREATER_THAN,        ">>")
TDES(T_GREATER_THAN_GREATER_THAN_EQUALS, ">>=")
TDES(T_LESS_THAN_EQUALS,                 "<=")
TDES(T_LESS_THAN_GREATER_THAN,           "<>")
TDES(T_LESS_THAN_LESS_THAN,              "<<")
TDES(T_LESS_THAN_LESS_THAN_EQUALS,       "<<=")
TDES(T_MINUS_EQUALS,                     "-=")
TDES(T_MINUS_GREATER_THAN,               "->")
TDES(T_PERCENT_EQUALS,                   "%=")
TDES(T_PLUS_EQUALS,                      "+=")
TDES(T_SLASH_EQUALS,                     "/=")
TDES(T_SLASH_SLASH,                      "//")
TDES(T_SLASH_SLASH_EQUALS,               "//=")
TDES(T_ETOODEEP,                         "error: too many indentation levels")
TDES(T_EDEDENT,                          "error: indentation level mismatch")
TDES(T_IDENTIFIER,                       "identifier")

TID(False,    T_False)
TID(None,     T_None)
TID(True,     T_True)
TID(and,      T_and)
TID(as,       T_as)
TID(assert,   T_assert)
TID(async,    T_async)
TID(await,    T_await)
TID(break,    T_break)
TID(class,    T_class)
TID(continue, T_continue)
TID(def,      T_def)
TID(del,      T_del)
TID(elif,     T_elif)
TID(else,     T_else)
TID(except,   T_except)
TID(finally,  T_finally)
TID(for,      T_for)
TID(from,     T_from)
TID(global,   T_global)
TID(if,       T_if)
TID(import,   T_import)
TID(in,       T_in)
TID(is,       T_is)
TID(lambda,   T_lambda)
TID(nonlocal, T_nonlocal)
TID(not,      T_not)
TID(or,       T_or)
TID(pass,     T_pass)
TID(raise,    T_raise)
TID(return,   T_return)
TID(try,      T_try)
TID(while,    T_while)
TID(with,     T_with)
TID(yield,    T_yield)

TDES(NUM_TOKENS, NULL)
/* clang-format on */
