TCHAR('%', T_PERCENT,      "%")
TCHAR('&', T_AMPERSAND,    "&")
TCHAR('(', T_LPAREN,       "(")
TCHAR(')', T_RPAREN,       ")")
TCHAR('*', T_ASTERISK,     "*")
TCHAR('+', T_PLUS,         "+")
TCHAR(',', T_COMMA,        ",")
TCHAR('-', T_MINUS,        "-")
TCHAR('.', T_DOT,          ".")
TCHAR('/', T_SLASH,        "/")
TCHAR(':', T_COLON,        ":")
TCHAR(';', T_SEMICOLON,    ";")
TCHAR('<', T_LESS_THAN,    "<")
TCHAR('=', T_EQUALS,       "=")
TCHAR('>', T_GREATER_THAN, ">")
TCHAR('@', T_AT,           "@")
TCHAR('[', T_LBRACK,       "[")
TCHAR(']', T_RBRACK,       "]")
TCHAR('^', T_CARET,        "^")
TCHAR('{', T_LCURLY,       "{")
TCHAR('|', T_BAR,          "|")
TCHAR('}', T_RCURLY,       "}")
TCHAR('~', T_TILDE,        "~")

TCHAR(256, T_INDENT,                     "indent")
TDES(T_DEDENT,                           "dedent")
TDES(T_STRING,                           "string")
TDES(T_BYTE_STRING,                      "byte string")
TDES(T_FORMAT_STRING,                    "format string")
TDES(T_RAW_STRING,                       "raw string")
TDES(T_UNICODE_STRING,                   "unicode string")
TDES(T_NEWLINE,                          "new line")
TDES(T_EOF,                              "end of file")
TDES(T_AMPERSAND_EQUALS,                 "&=")
TDES(T_ASTERISK_ASTERISK,                "**")
TDES(T_ASTERISK_ASTERISK_EQUALS,         "**=")
TDES(T_ASTERISK_EQUALS,                  "*=")
TDES(T_AT_EQUALS,                        "@=")
TDES(T_BAR_EQUALS,                       "|=")
TDES(T_CARET_EQUALS,                     "^=")
TDES(T_DOT_DOT_DOT,                      "...")
TDES(T_EQUALS_EQUALS,                    "==")
TDES(T_EXCLAMATIONMARKEQUALS,            "!=")
TDES(T_GREATER_THAN_EQUALS,              ">=")
TDES(T_GREATER_THAN_GREATER_THAN,        ">>")
TDES(T_GREATER_THAN_GREATER_THAN_EQUALS, ">>=")
TDES(T_LESS_THAN_EQUALS,                 "<=")
TDES(T_LESS_THAN_GREATER_THAN,           "<>")
TDES(T_LESS_THAN_LESS_THAN,              "<<")
TDES(T_LESS_THAN_LESS_THAN_EQUALS,       "<<=")
TDES(T_MINUS_EQUALS,                     "-=")
TDES(T_MINUS_GREATER_THAN,               "->")
TDES(T_PERCENT_EQUALS,                   "%=")
TDES(T_PLUS_EQUALS,                      "+=")
TDES(T_SLASH_EQUALS,                     "/=")
TDES(T_SLASH_SLASH,                      "//")
TDES(T_SLASH_SLASH_EQUALS,               "//=")
TDES(T_ETOODEEP,                         "error: too many indentation levels")
TDES(T_EDEDENT,                          "error: indentation level mismatch")
TDES(T_IDENTIFIER,                       "identifier")

TID(False,    T_FALSE)
TID(None,     T_NONE)
TID(True,     T_TRUE)
TID(and,      T_AND)
TID(as,       T_AS)
TID(assert,   T_ASSERT)
TID(async,    T_ASYNC)
TID(await,    T_AWAIT)
TID(break,    T_BREAK)
TID(class,    T_CLASS)
TID(continue, T_CONTINUE)
TID(def,      T_DEF)
TID(del,      T_DEL)
TID(elif,     T_ELIF)
TID(else,     T_ELSE)
TID(except,   T_EXCEPT)
TID(finally,  T_FINALLY)
TID(for,      T_FOR)
TID(from,     T_FROM)
TID(global,   T_GLOBAL)
TID(if,       T_IF)
TID(import,   T_IMPORT)
TID(in,       T_IN)
TID(is,       T_IS)
TID(lambda,   T_LAMBDA)
TID(nonlocal, T_NONLOCAL)
TID(not,      T_NOT)
TID(or,       T_OR)
TID(pass,     T_PASS)
TID(raise,    T_RAISE)
TID(return,   T_RETURN)
TID(try,      T_TRY)
TID(while,    T_WHILE)
TID(with,     T_WITH)
TID(yield,    T_YIELD)

TDES(NUM_TOKENS, NULL)
