/* Generated by scripts/gen_unicode_name_table.py - do not edit. */

#pragma once

#include <stdint.h>

#define UNICODE_NAME_BLOCK_SIZE      16
#define UNICODE_NAME_CODEPOINT_BITS  20
#define UNICODE_NAME_CODEPOINT_MASK  ((1u << 20) - 1u)
#define UNICODE_NAME_ENTRY_COUNT     32746
#define UNICODE_NAME_BLOCK_COUNT     2047
#define UNICODE_NAME_MAX_LENGTH      83
#define UNICODE_NAME_CODEPOINT_BYTES 81865

extern const uint8_t  unicode_name_codepoints[81865];
extern const uint32_t unicode_name_block_first_offsets[2047];
extern const uint8_t  unicode_name_block_first_names[54608];
extern const uint32_t unicode_name_block_data_offsets[2048];
extern const uint8_t  unicode_name_block_data[228482];
