/* Generated by scripts/gen_xid_table.py — do not edit. */
/* Unicode XID_Start / XID_Continue lookup table (Unicode 12.1.0) */

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define XID_SHIFT      7
#define XID_BLOCK_MASK 0x7f

extern const uint8_t xid_index1[8704];
extern const uint8_t xid_index2[5856];

static inline int is_xid_continue(uint32_t cp)
{
  if (cp >= 0x110000) return 0;
  uint32_t block = xid_index1[cp >> XID_SHIFT];
  uint32_t offset = cp & XID_BLOCK_MASK;
  uint8_t  packed = xid_index2[block * 32 + (offset >> 2)];
  return (packed >> ((offset & 3) * 2)) & 2;
}

static inline int is_xid_start(uint32_t cp)
{
  if (cp >= 0x110000) return 0;
  uint32_t block = xid_index1[cp >> XID_SHIFT];
  uint32_t offset = cp & XID_BLOCK_MASK;
  uint8_t  packed = xid_index2[block * 32 + (offset >> 2)];
  return (packed >> ((offset & 3) * 2)) & 1;
}

#ifdef __cplusplus
}
#endif
